name: Build and deploy Node.js app to Azure Web App - sample-deploy-13489686-app

on:
  push:
    branches:
      
main
workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      
uses: actions/checkout@v4

      
name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

      
name: npm install
      run: npm install --production

      
name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: |
          server.js
          package.json
          public/
          views/
          routes/
          models/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      
name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

      
name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8CFFB0D0CF1E4FE78DB9B16BA0050992 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FC2BC7AEFEFA4F0DA8D6C6A7952E6B4D }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_134D53CDEFB54669ACDAB60E3734A630 }}

      
name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'sample-deploy-13489686-app'
        slot-name: 'Production'
        package: .
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sample-deploy-13489686-app'
          slot-name: 'Production'
          package: .

          
